################################################################
#                                                              #
#            BISTRO TPE OPTIMIZER/RS SETTINGS                  #
#                                                              #
#    This file contains all parameters for BISTRO scenarios    #
#                        evaluation                            #
#                                                              #
#                                                              #
################################################################

# Before running any optimization, please refer to this folder's
# README file to properly install and configure BISTRO, Hyperopt
# and Mongodb

###################### BASIC CONFIGURATION #####################

#BISTRO Installation directory
BEAM_PATH: "/home/ubuntu/BISTRO/"

#Hyperopt installation path - Default : ~/.local/bin
HYPEROPT_PATH: "/home/ubuntu/.local/lib/python3.6/site-packages/hyperopt/"
# HYPEROPT_PATH: "/home/ubuntu/.local/bin/"

# hyperopt-mongo-worker executable is actually here
HYPEROPT_MONGO_WORKER_PATH: "/home/ubuntu/.local/bin/"


#Experiment key: each experiment must have a unique identification
#key. It can be any string that you MUST define here:
UNIQUE_KEY: "Optim_cordon"

################## EXPERIMENT I-O FOLDERS ######################

#Samples output folder
RESULTS_PATH: "/home/ubuntu/HV_TEST/"

#Folder containing Sioux Fall's network.csv file
NETWORK_PATH: "/home/ubuntu/BISTRO/BISTRO-Optimization-Library/fixed_data/network.csv"

#Results standardization file, used for optimization only - not RS -
STANDARDS: "/home/ubuntu/BISTRO/BISTRO-Optimization-Library/per_mile/per_mile_stds.csv"


################# OPTIMIZATION SETTINGS #######################

#Number of individual agents in the simulation; currently only 15k works
SAMPLE_SIZE: "15k" # 1k

#Number of iterations per sample. 30 is usually enough to converge
SIMULATION_ITERS: 30

#Number of optimization samples to get 
NUMBER_OF_SAMPLES: 20

#This file contains the the definition of the optimization KPI
OPTIMIZATION_KPI_FILE: "optimization_kpi.py"

#Maxmimum price per mile (in $) that can be applied as toll
MAX_TOLL: 10

# Toggle Hypervolume optimization on/off
HYPERVOLUME: True
