################################################################
#                                                              #
#            BISTRO TPE OPTIMIZER/RS SETTINGS                  #
#                                                              #
#    This file contains all parameters for BISTRO scenarios    #
#                        evaluation                            #
#                                                              #
#                                                              #
################################################################

# Before running any optimization, please refer to this folder's
# README file to properly install and configure BISTRO, Hyperopt
# and Mongodb

###################### BASIC CONFIGURATION #####################

#BISTRO Installation directory
BEAM_PATH: "/Users/makenaschwinn/Desktop/bistro/BISTRO/"

#Hyperopt installation path - Default : ~/.local/bin
# HYPEROPT_PATH: "/Users/makenaschwinn/anaconda3/lib/python3.7/site-packages/hyperopt/"
# HYPEROPT_PATH: "/Users/makenaschwinn/anaconda3/bin/"
HYPEROPT_PATH: "/Users/makenaschwinn/anaconda3/envs/bistro/lib/python3.7/site-packages/hyperopt/"
# HYPEROPT_PATH: "/Users/makenaschwinn/anaconda3/envs/bistro/lib/python3.7/"

HYPEROPT_MONGO_WORKER_PATH: "/Users/makenaschwinn/anaconda3/envs/bistro/bin/"

#Experiment key: each experiment must have a unique identification
#key. It can be any string that you MUST define here:
UNIQUE_KEY: "Optim_cordon"

################## EXPERIMENT I-O FOLDERS ######################

#Samples output folder
RESULTS_PATH: "/Users/makenaschwinn/Desktop/bistro/CORDON_1103_v5/"

#Folder containing Sioux Fall's network.csv file
NETWORK_PATH: "/Users/makenaschwinn/Desktop/bistro/BISTRO/BISTRO-Optimization-Library/fixed_data/network.csv"

#Results standardization file, used for optimization only - not RS -
STANDARDS: "/Users/makenaschwinn/Desktop/bistro/BISTRO/BISTRO-Optimization-Library/cordon/cordon_stds.csv"


################# OPTIMIZATION SETTINGS #######################

#Number of individual agents in the simulation; currently only 15k works
SAMPLE_SIZE: "15k" # 1k

#Number of iterations per sample. 30 is usually enough to converge
SIMULATION_ITERS: 10

#Number of optimization samples to get 
NUMBER_OF_SAMPLES: 20

#This file contains the the definition of the optimization KPI
OPTIMIZATION_KPI_FILE: "optimization_kpi.py"

#Maxmimum price per mile (in $) that can be applied as toll
MAX_TOLL: 10

# Toggle Hypervolume optimization on/off
HYPERVOLUME: True
